data:
  processed_dataset_path: processed_data
  raw_dataset_path: ShuttleCockFrameDataset
device: cuda
model:
  cnn_backbone: resnet18
  input_size: 224
  sequence_length: 5
  transformer_layers: 2
  transformer_nhead: 4
  type: hybrid
  use_frame_diff: true
  use_trajectory_inpainting: true
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.0005
  num_workers: 16
  persistent_workers: true
  scheduler: cosine
  warmup_epochs: 5
  weight_decay: 0.01
