data:
  processed_dataset_path: processed_data
  raw_dataset_path: ShuttleCockFrameDataset
device: cuda
model:
  cnn_backbone: efficientnet_b3
  input_size: 224
  sequence_length: 5
  transformer_layers: 4
  transformer_nhead: 8
  dropout: 0.2
  attn_dropout: 0.1
  type: hybrid
  use_frame_diff: true
  use_trajectory_inpainting: true
  heatmap_size: 56
training:
  batch_size: 32  # Increased for better GPU utilization (was 8)
  epochs: 50
  learning_rate: 0.0005
  num_workers: 16  # Increased for faster data loading (was 10)
  persistent_workers: true
  scheduler: cosine
  warmup_epochs: 5
  weight_decay: 0.01
  gradient_clip_val: 1.0
  loss_weights:  # Loss weights for BCE, MSE, and smooth losses
    bce: 1.0
    mse: 10.0
    smooth: 0.05
  augmentations:
    mixup: true
    cutmix: true
    random_erasing: true
    color_jitter: true
    blur: true
    noise: true
