data:
  processed_dataset_path: processed_data
  raw_dataset_path: ShuttleCockFrameDataset
device: cuda
model:
  cnn_backbone: efficientnet_b3
  input_size: [360, 640]  # height, width
  sequence_length: 5
  heatmap_size: 64
  feature_dim: 256
  transformer_nhead: 8
  transformer_layers: 4
  dropout: 0.2
  attn_dropout: 0.1
  use_optical_flow: true
  predict_uncertainty: true
training:
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.0001
  epochs: 100
  num_workers: 4
  gradient_clip_val: 1.0
  
  # Loss function weights
  loss_weights:
    bce: 1.0
    focal_bce: 1.5
    mse: 1.0
    focal: 0.8
    smooth: 0.15
    smooth_l1: 0.5
    uncertainty: 0.2
  
  # Focal loss parameters
  focal_gamma: 2.0

# Post-processing configuration for trajectory smoothing
post_processing:
  # Smoothing options: 'kalman', 'savgol', 'moving_avg'
  smooth_mode: 'kalman'
  smooth_window_size: 5  # Window size for smoothing filters
  
  # Inpainting options: 'linear', 'spline', 'pchip'
  inpaint_method: 'spline'
  
  # Visibility processing
  visibility_threshold: 0.5  # Threshold for binary visibility
  visibility_smooth_window: 3  # Window size for visibility smoothing
